# The original way with ./nginx.conf:/etc/nginx/nginx.conf:ro was causing issues with the nginx volume mounting. 
# Probably because we have jenkins inside the container and because we are using docker-in-docker.
FROM nginx:1.27.4-alpine3.21

# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static files
COPY ./static /usr/share/nginx/static