# Application manifest to bootstrap infrastructure at startup
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@gitlab.com:andishubash/gamecon-gitops.git
    path: "infra-apps"
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true