apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@gitlab.com:andishubash/gamecon-gitops.git
      targetRevision: main
      path: KPS/charts/kube-prometheus-stack
      helm:
        valueFiles:
          - "../../kps-values.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true