apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gamecon
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"  # Deploy after infrastructure
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@gitlab.com:andishubash/gamecon-gitops.git
    targetRevision: main
    path: gamecon
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
