apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingress.issuer }}
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: {{ .Values.certManager.server }}
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.ingress.issuer }}-private-key
    solvers:
      - http01:
          ingress:
            class: nginx