apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}-monitor
  namespace: prometheus  
  labels:
    app: {{ .Values.name }}
    release: kps-application  
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}  
  selector:
    matchLabels:
      app: {{ .Values.name }}  
  endpoints:
  - port: http  
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s