{{- if .Values.postgresql.namespaceOverride }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.postgresql.namespaceOverride }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: IgnoreExtraneous=true
    argocd.argoproj.io/sync-wave: "0"  
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
    type: Opaque
  
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: andi/gamecon/database 
        property: password
        
    - secretKey: REPLICATION_PASSWORD
      remoteRef:
        key: andi/gamecon/database 
        property: replication_password
{{- end }}